//Categories
export const GET_CATEGORIES = 'GET_CATEGORIES'

//Brands
export const GET_BRANDS = 'GET_BRANDS'

//Weights
export const GET_SIZES = 'GET_SIZES'

//Products
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCT_REQUESTS = 'GET_PRODUCT_REQUESTS'

//Stock
// export const SUBMIT_REQUEST ='SUBMIT_REQUEST'
export const SUBMIT_STOCK = 'SUBMIT_STOCK'

//Return Product
export const SUBMIT_RETURN_PRODUCT ='SUBMIT_RETURN_PRODUCT'

//Sold Product
export const SUBMIT_SOLD_PRODUCT ='SUBMIT_SOLD_PRODUCT'

//Mobile Center
export const MOBILE_SUBMIT_REQUEST ='MOBILE_SUBMIT_REQUEST'
export const MOBILE_SUBMIT_RETURN_PRODUCT ='MOBILE_SUBMIT_RETURN_PRODUCT'
export const MOBILE_SUBMIT_SOLD_PRODUCT ='MOBILE_SUBMIT_SOLD_PRODUCT'

//City Hall
export const CITYHALL_SUBMIT_REQUEST ='CITYHALL_SUBMIT_REQUEST'
export const CITYHALL_SUBMIT_RETURN_PRODUCT ='CITYHALL_SUBMIT_RETURN_PRODUCT'
export const CITYHALL_SUBMIT_SOLD_PRODUCT ='CITYHALL_SUBMIT_SOLD_PRODUCT'

//ADM-Mobile
// export const ADM_MOBILE_SUBMIT_STOCK ='ADM_MOBILE_SUBMIT_STOCK'
